x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1-python3.11
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:password123@postgres_db:5432/airflow_db
    - AIRFLOW__WEBSERVER__SECRET_KEY=danone_secret_key_2026
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - _PIP_ADDITIONAL_REQUIREMENTS=dbt-postgres pandas psycopg2-binary azure-storage-blob
  volumes:
    - ./dags:/opt/airflow/dags
    - .:/opt/airflow/project
    - ./logs:/opt/airflow/logs
  depends_on:
    postgres_db:
      condition: service_healthy

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest # Forzamos la última
    command: azurite --skipApiVersionCheck --blobHost 0.0.0.0 --loose
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS=account1:key1

  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash -c "airflow db migrate && (airflow users create --username admin --firstname Manuel --lastname Alen --role Admin --email admin@example.com --password admin || true)"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports: ["8080:8080"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully